import type { Metadata } from 'next';
import { inter, segoe } from 'utils/helpers/fonts';
import { ChakraProvider } from '@chakra-ui/react';

import 'styles/globals.scss';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${segoe.variable} ${inter.variable} ${inter.className}`}
      >
        <ChakraProvider>{children}</ChakraProvider>
      </body>
    </html>
  );
}
